### ISSUE TITLE
homekit not turning on thermostat

### ISSUE THREAD

**Issue by mrobertson1992** [mark-wade/homebridge-hive#11]
after updating I am unable to turn on the heating from the home app, hive works fine using the hive app or the thermostat and the correct status is displayed in the home app when heating and I can turn the temperature up or down. I can turn it off using the home app the only thing it won't do is turn hive on if it is in the off state.. any ideas?

**Comment by mark-wade** [comment]
If you look at the console/terminal where homebridge is running, what is the output when you try to toggle it?
