### ISSUE TITLE
Request: Support for Hive Active Plug and Bulb

### ISSUE THREAD

**Issue by mehtaman** [mark-wade/homebridge-hive#13]
Hi

As per the title... are you able to look into adding:
Hive Active Plug
On/Off command

Hive Bulb
On/Off command
0-100% Brightness slider

Thank you

**Comment by mark-wade** [comment]
The plug I am hoping to work on.

The bulb I have no plans to support (I don't have any Hive bulbs, using Hue throughout my home).

I'll add something to the readme about this because I get asked a lot :p

**Comment by mehtaman** [comment]
Great, Thanks for taking time to work on this when you can :+1: 

I was reading through this API the other day to see if I could add the device list to your code but my coding skills are very very limited :(

[http://www.smartofthehome.com/2016/05/hive-rest-api-v6/ ](http://www.smartofthehome.com/2016/05/hive-rest-api-v6/ )

**Comment by mark-wade** [comment]
Yeah that's the API I'm using. The main issue I have to overcome is that currently the plugin is designed to just find one device (I kind of hacked it up for people with multiple thermostats) whereas I really need to re-engineer it to create a bridge device (for the hub) and then add all the Hive products as children of that... and then having a device to test with.
