### ISSUE TITLE
Hot water

### ISSUE THREAD

**Issue by cpives2008** [mark-wade/homebridge-hive#14]
Is it possible for this to control hot water too?

**Comment by mark-wade** [comment]
Not currently. HomeKit doesn't _really_ have a matching type, though I might look into using just a switch mapped to the hot water boost functionality.

**Comment by mpjalexander** [comment]
Rather than linking a HomeKit switch to the Hive’s hot water boost (which will automatically turn off after a set period), can’t you just map it the manual on or off that you can set via the Hive app? In other words, the hot water would be a simple switch: either off or on.
