### ISSUE TITLE
Crashing out the blue. Nothing changed

### ISSUE THREAD

**Issue by scbbaird** [mark-wade/homebridge-hive#21]
Nothing changed in my setup and then crashing when I discover thermostat in homekit.

Running on Windows 10 with all the correct versions of support systems.

Getting the following error :

C:\Users\scbbaird\AppData\Roaming\npm\node_modules\homebridge-hive\index.js:197
                                        if ( data.attributes.stateHeatingRelay.reportedValue == 'OFF' ) {
                                                  ^

TypeError: Cannot read property 'attributes' of null
    at HiveThermostat.<anonymous> (C:\Users\scbbaird\AppData\Roaming\npm\node_modules\homebridge-hive\index.js:197:16)
    at HiveThermostat.<anonymous> (C:\Users\scbbaird\AppData\Roaming\npm\node_modules\homebridge-hive\index.js:116:30)
    at HiveThermostat.<anonymous> (C:\Users\scbbaird\AppData\Roaming\npm\node_modules\homebridge-hive\index.js:139:4)
    at Request.self.callback (C:\Users\scbbaird\AppData\Roaming\npm\node_modules\homebridge-hive\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\scbbaird\AppData\Roaming\npm\node_modules\homebridge-hive\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\scbbaird\AppData\Roaming\npm\node_modules\homebridge-hive\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by gbsingh1993** [comment]
Hi.

Im having the same issue. Homebridge will start as normal and as soon as I open the home app it crashes. Have you found a fix for it yet??

**Comment by bendodson** [comment]
Experiencing the same issue here - started a couple of days ago.

**Comment by scbbaird** [comment]
No fix as yet. not sure it ever will be as last update to this module was a year ago.  Anyone know if the developer is still maintaining?

**Comment by mark-wade** [comment]
Hive seem to have changed their API. Unfortunately, I no longer use a Hive thermostat as I moved house so I am not maintaining this project any more.

**Comment by scbbaird** [comment]
Hi Mark thanks for getting back and taking the time out to do so.  Is there an alternative you would recommend? Loved the project and was very useful sorry to see it die! Thanks for any help.

**Comment by mpjalexander** [comment]
I suggest [HomeBridge](https://www.npmjs.com/package/homebridge) and the [homebridge-hive](https://www.npmjs.com/package/homebridge-hive) plugin.

**Comment by Venger2005** [comment]
@mpjalexander You do realise you've just linked to this very plugin which currently has issues as highlighted in this thread by the OP and others, and which the author has now flagged as no longer being maintained?

**Comment by mpjalexander** [comment]
Doh! I was getting confused with another Hive/HomeKit solution ([HiveKit](https://github.com/njpatel/hivekit)). Comment deleted.

As an aside, due to the lack of (official or unofficial) support for HomeKit, I’ve very recently dumped Hive in favour of Tado.

**Comment by richminust** [comment]
I'm gutted this plugin is no longer working, I had Hive (multi-zone) installed yesterday with the intention of running this. Mark, if it helps, I'm a software/web developer so I know my way around developer tools, json etc. I wouldn't know where to start when developing a plugin for HomeBridge, however I could help debug/get you the info you need using my own login to the Hive web service and also test if you were still interested in maintaining your plugin? Hopefully Hive haven't changed too much :(

**Comment by scbbaird** [comment]
@richminust if you ever get this working again I would be interested.  Not a developer in anyway so depended on the good will of others here. 

I have linked my Hive to Alexa now and all working fine from there. I have also now linked ALL of my automations to now run on Alexa which to be honest is much simpler.   (HUE, Hive, Sonos, Wemo and Harmony Hub), they all just work and I can do fancy things like automate lights and turning on the devices all at the same time without much hassle. So I would recommend going to buy Alexa dots and sticking them around the house you really only need 3 or 4 and it all just works!  

Looks like Apple homekit is really dead and not worth the extra hassle it presents when it comes to this type of integration.

**Comment by mark-wade** [comment]
Hmm... I'd really be stabbing in the dark. If you're familiar with web development though @richminust, you might find it easier than you expect! Here's a good guide to getting started: http://blog.theodo.fr/2017/08/make-siri-perfect-home-companion-devices-not-supported-apple-homekit/

**Comment by richminust** [comment]
Thanks @mark-wade, I'll take a look, although when looking at the source of your project, it's not the kind of thing I do on a daily basis so out of my comfort zone.

@scbbaird, I have linked Hive to Alexa also, I have 7 Echos and Dots scattered around the house and they work like a charm. I also have 5 video cameras for which I've used HomeBridge so they show up in HomeKit, love seeing the video feed on my phone for all 5 cams even though they are from different manufacturers. I also have Elgato door and window sensors plus Hue motion/temp detectors and Hue lights, oh and Belkin Wemo sockets, a Harmony Hub and last but not least an AppKettle. I moved my automations away from Alexa once I discovered HomeBridge and started to use HomeKit more, I'm also a bit of an Apple geek. I was hopeful that Homekit with HomeBridge was the solution to pull everything in to one place, it's done a great job so far, just need the Hive heating on there too!

**Comment by smeathers** [comment]
Thanks @mark-wade for the link on getting started, I'll try and look through it.  I did some debugging and extra logging on it Monday night but didn't get too far.  I'm guessing the returned json object has changed.  I want to have another crack at trying to fix it and will try and find some time over the weekend.  I've seen it fall over in two difference places in the code but don't have the information with me on this computer.

**Comment by richminust** [comment]
@smeathers, I've had a quick look and I too think the json response has changed in structure, hopefully it's relatively easy to fix if that is the case. Would be great if you can come up with a fix.

**Comment by JamesFowler42** [comment]
Hi. I've fixed the problem with this and it's now working on my system. 

I'll put a pull request in to bring this back to @mark-wade's branch.

In the meantime you can do this:
sudo npm install -g git+https://git@github.com/JamesFowler42/homebridge-hive.git

The structure change seems to be they have put NodeType under attributes and given it reportedValue and displayValue.

I've also updated homebridge-hive-motion and you can get this (before I push to npm) using:
sudo npm install -g git+https://git@github.com/JamesFowler42/homebridge-hive-motion.git

**Comment by gbsingh1993** [comment]
@JamesFowler42 thats amazing. Thank you so much for this. Once its up through npm could you please let us know and then I can get it installed. Amazing work 👍

**Comment by JamesFowler42** [comment]
@gbsingh1993 I need @mark-wade to put this up under npm unless I pick another name (ugh - there are enough things up there). I would suggest using the npm install from GitHub command I've given.

**Comment by mark-wade** [comment]
If you submit a PR I'll sort that out :)

**Comment by JamesFowler42** [comment]
Magic!

**Comment by scbbaird** [comment]
@JamesFowler42 Wow thank you so much, Hive is Live!  Installed new package as above and all working now.
