### ISSUE TITLE
Support for Hive TRVs

### ISSUE THREAD

**Issue by mayhew132** [mark-wade/homebridge-hive#25]
Hi Mark,

Thanks for developing this plugin, I've been using it for a while now. 

Hive have recently brought out TRVs for radiators, allowing granular control room-by-room - I'd be happy to help with sourcing a TRV for you to look into building this into your solution (if you have the time)?

Cheers,
Guy

**Comment by mark-wade** [comment]
Unfortunately I have now moved home and my new home (in Australia) doesn't have any central heating... so I'm no longer using this plugin and wouldn't have any radiators to test on.

Sorry I can't help.

**Comment by mayhew132** [comment]
No worries Mark - enjoy Australia and thanks for your help 👍
