### ISSUE TITLE
Target Temperature Incorrect

### ISSUE THREAD

**Issue by SneakyChilli** [mark-wade/homebridge-hive#3]
Hi

The target temp is always set to the last value entered in the IOS home app. Should this be the current Hive target (per the schedule or override)?

E.g. Last night I set the temp to 22 via Home. (Which worked great). 

Now the target temp as set by the Hive schedule is 18, but the Home me still shows 22. 

Should the plugin be getting the current target temp from Hive?

Cheers

**Comment by mark-wade** [comment]
Hmm... I only ever use manual mode so hadn't really thought about this.

If you're on schedule and you change the temperature manually, what would you expect to happen? Override for a period of time, or until the next schedule time, or something else?

**Comment by SneakyChilli** [comment]
I would expect override until next schedule change. This is how the Hive thermostat works. 

Although a 'boost for 60 mins' function would be a useful extra.

**Comment by mark-wade** [comment]
Try now.

**Comment by SneakyChilli** [comment]
Brilliant. Thanks Mark!
