### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by mrobertson1992** [mark-wade/homebridge-hive#4]
Since this afternoon hive is not responding in the home app any ideas? I have update to the latest version but no luck

**Comment by mark-wade** [comment]
What do you see in the terminal where you ran `homebridge`?

**Comment by mrobertson1992** [comment]
I think I figured it out, if the heating set is below the current room temp the home app doesn't like it so increasing the temp and then turning back makes it respond. On another note since running homebridge in systemctl I can't access hive remotely from the home app. Any ideas?

**Comment by mark-wade** [comment]
That's strange - it works fine for me (it shows a orange icon - to indicate the heating is on - if the current room temperature is below the target, and a green one otherwise).

Is your Hive set to manual or schedule? Is there any output in the terminal?

**Comment by mrobertson1992** [comment]
It seems to be working fine now, so makes me think there was an issue with my isp earlier
