### ISSUE TITLE
Multiple thermostats

### ISSUE THREAD

**Issue by EssendonPhoto** [mark-wade/homebridge-hive#5]
Hi

I have two heating zones (upstairs + downstairs), plus use Hive for hot water control 

I have tried using the "name" field to pick up the different controls, without success - I simply got the same (first) zone three times. I know that the additional thermstats are addressable through the API (discussed at http://www.smartofthehome.com/2016/05/hive-rest-api-v6/ in case you hadn't seen) - is it possible to extend your plugin?

Also, do you plan to extend to include some form of implementation of the Boost function? This may be challenging in the Homekit format

Cheers

**Comment by mark-wade** [comment]
I knew someone would hit this 😂

Can you tell me what the output of the API is at `/nodes`?

**Comment by EssendonPhoto** [comment]
I can - though at some 4000 lines I'd prefer to email it. (Not least because I wojuld rather not expose publicly any potentially personal info). Got an address that I can use?

**Comment by mark-wade** [comment]
m.wade@me.com

**Comment by EssendonPhoto** [comment]
Sent
